### ISSUE TITLE
(meta) How to create a Batch checklist ✅

### ISSUE THREAD

**Issue by phipsae** [phipsae/testsss#43]
## How to create a Batch

- [x] Update code with latest SE-2 code (**do this before creating the template on the new repo) and push code
```git merge se2/main```
- [x] Create a template (private) in name of BuidlGuidl from this repo. Name it `batchX.buidlguidl.com`
- [x] Settings -> Enable discussions -> Set up Discussions
- [x] Create _Introductions_ topic in discussions (e.g. https://github.com/BuidlGuidl/batch0.buidlguidl.com/discussions/1)
- [x] Create issues (reverse order so they show in the _right_ order)
- [x] Create/remove issue labels (`good first issue`, `smart contract`, `frontend`,`for all`)
- [x] Update links *within* issues to point to the new repo's issues (issues: 4 -> Personal Page, 5 -> check in, 6 -> check-in, 7 -> check-in, create personal page)
- [x] Update links *in* README to point to the new repo's issues
- [x] Connect to Vercel & deploy
- [x] Connect Github to Vercel (on the project main page --> click button)
- [x] Add the following to the root directory `packages/nextjs` (vercel settings)
- [x] Add NEXT_PUBLIC_ALCHEMY_API_KEY in Vercel
- [x] Point `batchX.buidlguidl.com` domain to Vercel (ask Austin). And you add the domain to the project in vercel. 
- [x] Change Batch number in NextJS `page.tsx`
- [x] Change `BATCH_NUMBER` in hardhat deploy script
- [x] Deploy OP contract, verify, and add *both* addresses to `externalContracts.ts` (Registry and GraduationNFT)
- [x] Update contract links on "Check-in with the BatchRegistry contract" issue
- [x] Update contract links on "Batch Graduation NFT" issue
- [x] Add builders to the allowList (so they can check-in)
- [x] Fund OP contract: 0.01 oETH * number of builders in the batch from Safe Contract, you can use [split.buidlguidl.com](url)
 for it.
- [x] Send builders gas: send 0.005 oETH to _each_ builder in the batch. ([example](https://optimistic.etherscan.io/tx/0x546bfa05235c139d7a8a94c8ba3ba5b4e5856b84753ba3c0ddd9314e68de3275))
- [ ] Make the repo public when ready.
- [ ] Toggle isOpen on the BatchRegistry contract to `true`
- [ ] Ensure that `toggleGraduationOpenStatus` in the BatchRegistry contract is set to `false`

**--- 1 week after Batch started preparation for next Batch ---**

- [ ] Create new telegram group for Next Batch with respective logo
- [ ] Toggle the new TG group's setting: Chat History for New Members to `Visible`
- [ ] Add appropriate admins in the channel
- [ ] Create opening message and pin it in the group
- [ ] Create a new batch in the BuidlGuidl app, with the newly generated TG invite link and the correct start date (typically starting on a Monday, one month after the previous batch's start date) - [see how to video](https://github.com/user-attachments/assets/7ac4a8f7-e63a-42d4-a1ca-44e9f377a8ce)

**--- 2 weeks after Batch started ---**

- [ ] Airdrop ETH for ENS to people who've checked in *after* asking them to paste their BG profile in the Batch chat
- [ ] Toggle isOpen on the BatchRegistry contract to `false`

**--- At the end of batch (ca. 3 weeks in) ---**

- [ ] Toggle `toggleGraduationOpenStatus` to enable minting of graduation NFTs (set to `true`)
- [ ] Send a final message notifying users about the NFT minting and the opportunity to apply for grants
- [ ] Update the status of users from `participant` to `graduate` in BuidlGuidl app for those who have created a personal page and checkedIn in the respective "Batch X."  (See how to [video link](https://github.com/user-attachments/assets/2d35913a-12b8-4191-b3fa-95c4d9a300d8) and 
[link to google doc](https://docs.google.com/spreadsheets/d/1jKi6phXp69OSkPmyI9W8s7IMCEJz7jOL2S6w1iC8lMs/edit?gid=1186758557#gid=1186758557))
- [ ] Give your opinion on all participants in the google doc and assess if you would give them a grant

**Telegram Group**

```
🏰 BuidlGuidl: 👨‍👩‍👧‍👦 Batch #X 🧑‍🏫
```

Images:
![Screen Shot 2024-01-11 at 9 58 34 AM](https://github.com/BuidlGuidl/batch-template/assets/2653167/cbdcc679-30cb-4f27-864f-535ce19701a0)

![Screen Shot 2024-01-02 at 11 35 01 AM](https://github.com/BuidlGuidl/batch-template/assets/2653167/f24c40e4-ca2d-44cc-9c1f-9fc9050850ae)

**Pinned telegram message**
```
👨‍👩‍👧‍👦 BuidlGuidl Batch #X 🏆

🍾 🎊 👏 🎉 🥂 🎊👏🔥 🥂 🎉 👏 🍾

👋 Welcome! 

🧑‍💻 To help you get started in onchain development, we've created the BG  batch program. Dive into end-to-end dApp development, receive mentorship from BG members, and learn how to collaborate with fellow developers in open-source projects.

📡 We’re here to help you find your next rabbit hole! 🐇⚗️🛰

🧑‍🔬 We will use GitHub as our main coordination tool to keep this room high signal to noise, but please ask questions here along the way! 👩‍🏫✊

🫡 On Feb Xth, we will share the batch's Github repo with a comprehensive ReadMe with all the details!
```

and maybe 

```
📝 post your BG profile link here so we can get your address to send some ETH for gas and an ENS address!
```

Pinned message 2: starting with link to repo. **Change X to batch number in three places**
```
👨‍👩‍👧‍👦 BuidlGuidl Batch #X 🏆

🍾 🎊 👏 🎉 🥂 🎊👏🔥 🥂 🎉 👏 🍾

🔥 The Batch #X challenge repo is live!!

🧪 Let’s coordinate around this github repo:
https://github.com/BuidlGuidl/batchX.buidlguidl.com

👀 Check out the open issues, some are for everyone to do as an intro and others just need one champion to bring us together. You can find all the details on the README 🕵️🔎

🛠 We are sending a small amount of oEth (eth on optimism) to each of your addresses to use as gas to complete the open issues ⛽️🚀
```

**Manually onboarding**

```

🏆 good work on the speedrun!

We are gathering recent builders in a telegram channel to help get you started with next steps... join us here: https://t.me/+ght8cLIAzOg0MDkx

(There’s a tiny ETH scholarship in it for you if you join and post your BG profile! 🧑‍🔬 )

also hit me up if you have any questions! keep going!!!

```

and then when I send funds:

```
🚢 we just scholarshipped some ETH to everyone who checked in and didn't have an ENS yet! 

Grab an ENS for your BG profile and bridge a little to OP too. Let us know what ENS name you choose!
```

Transition to "final projects" after the repo's issues are done
**Note: Make sure to update the `batchX` in the link to a specific number, e.g. `batch5`.**
```
All of this repo's issues have been closed thanks to your collective effort! 🥳 
You all did a great job in this Batch! 👾👾👾
This is an important step in your journey to becoming an open-sourcerer 🧙 

What next? Starting today, you can start submitting your final project idea on https://grants.buidlguidl.com. We'll review them next week.

More info here: https://github.com/BuidlGuidl/batchX.buidlguidl.com/issues/2
```

When the batch is ending:
(looks better if you hyperlink part of the last sentence instead of pasting the full URL)
```
🥳 Congratulations for completing BG’s Batch Program!

At this point you’ve SpeedRunEthereum, contributed to an open-source repo, and made a few frens along the way. Now that our time together is coming to an end 🥲, let’s talk about what happens next.

- Looking for a full-time job in web3?
- Interested in winning bounties, grants, or hackathons? 
- Looking to learn more about smart contracts, auditing, or zk?

We made a special list of resources for Batch graduates to guide the next steps on your journey down the rabbit hole 🐰🕳️ 
https://buidlguidl.notion.site/Next-Steps-for-BG-Batch-Members-627956c3e00c42ab82707d4bdd04bc8e
```

**extra: wallet talk***
```
🧑‍🏫 alright Batch #X it's time to have that talk...

😅 sometimes people sign up for BuidlGuidl accounts that started as dev accounts...

🥵 a small percent of BG accounts end up getting compromised because devs put their private key in an ENV file or it ends up on GitHub somehow 

😎 it's very important that you keep accounts with >$100 very safe 
(No copy pasting it around, no putting it in a plaintext file, etc)

🙋 if you have any questions about self-custody, feel free to ask in this chat or DM

🦉 if you want to be really safe, you might even deploy your own gnosis safe
```
